# Generated by Django 3.1 on 2024-03-30 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='dateadded',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartt',
            new_name='cart',
        ),
    ]
